print("Welcome to Winai Shop")
print("-------------------------------------------------")
print("Apple x", 3, 30, "THB - ", 3*30, "THB")
print("Banana x", 1, 10, "THB - ", 1*10, "THB")
print("Gabage Bag x", 1, 49, "THB - ", 1*49, "THB")
print("Pure Water pack x", 3, 48, "THB - ", 3*48, "THB")
print("Coconut Water x", 6, 10, "THB - ", 6*10, "THB")
print("-------------------------------------------------")
print("Total - ", (3*30)+(1*10)+(1*49)+(3*48)+(6*10), "THB")
print("Thank you : Winai Shop")
